FROM nginx:alpine

#COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
#COPY /nginx.conf /etc/nginx/conf.d/default.conf
COPY /nginx.conf /etc/nginx/conf.d

#COPY --from=build /app/dist /usr/share/nginx/html
#COPY /dist /usr/share/nginx/html

EXPOSE 1443/tcp
CMD ["/bin/sh", "-c", "exec nginx -g 'daemon off;';"]
WORKDIR /usr/share/nginx/html